<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-25T00:33:23 IST" name="Realtime" finished-at="2024-06-25T00:34:10 IST" duration-ms="47257">
    <groups>
      <group name="Errorvalidation">
        <method signature="Standalone_convertTest.purchaseOrder(java.util.HashMap)[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" name="purchaseOrder" class="SeleniumRealtime.testcases.Standalone_convertTest"/>
        <method signature="Error_Validation_Test.logininvalid_Credencial()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" name="logininvalid_Credencial" class="SeleniumRealtime.testcases.Error_Validation_Test"/>
      </group> <!-- Errorvalidation -->
      <group name="multipledata">
        <method signature="Standalone_convertTest.purchaseOrder(java.util.HashMap)[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" name="purchaseOrder" class="SeleniumRealtime.testcases.Standalone_convertTest"/>
      </group> <!-- multipledata -->
    </groups>
    <test started-at="2024-06-25T00:33:23 IST" name="Errorvalidation" finished-at="2024-06-25T00:33:43 IST" duration-ms="20742">
      <class name="SeleniumRealtime.testcases.Error_Validation_Test">
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:23 IST" name="launching_App" finished-at="2024-06-25T00:33:28 IST" duration-ms="5765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method retried="true" signature="logininvalid_Credencial()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:28 IST" name="logininvalid_Credencial" finished-at="2024-06-25T00:33:30 IST" duration-ms="1639" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumRealtime.testcases.Error_Validation_Test.logininvalid_Credencial(Error_Validation_Test.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logininvalid_Credencial -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:30 IST" name="close" finished-at="2024-06-25T00:33:30 IST" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:30 IST" name="launching_App" finished-at="2024-06-25T00:33:34 IST" duration-ms="3689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method signature="logininvalid_Credencial()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:34 IST" name="logininvalid_Credencial" finished-at="2024-06-25T00:33:35 IST" duration-ms="817" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumRealtime.testcases.Error_Validation_Test.logininvalid_Credencial(Error_Validation_Test.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logininvalid_Credencial -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:35 IST" name="close" finished-at="2024-06-25T00:33:36 IST" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:36 IST" name="launching_App" finished-at="2024-06-25T00:33:40 IST" duration-ms="4307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method signature="productErrorValidation()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:40 IST" name="productErrorValidation" finished-at="2024-06-25T00:33:43 IST" duration-ms="3060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Error_Validation_Test@7862f56]" started-at="2024-06-25T00:33:43 IST" name="close" finished-at="2024-06-25T00:33:43 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- SeleniumRealtime.testcases.Error_Validation_Test -->
    </test> <!-- Errorvalidation -->
    <test started-at="2024-06-25T00:33:23 IST" name="Convertedcode" finished-at="2024-06-25T00:34:10 IST" duration-ms="47257">
      <class name="SeleniumRealtime.testcases.Standalone_convertTest">
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:33:23 IST" name="launching_App" finished-at="2024-06-25T00:33:28 IST" duration-ms="5279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method signature="purchaseOrder(java.util.HashMap)[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:33:28 IST" name="purchaseOrder" data-provider="getdata" finished-at="2024-06-25T00:33:44 IST" duration-ms="15973" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=IPHONE 13 PRO, password=Welcome@123, email=antony@yopmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseOrder -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:33:44 IST" name="close" finished-at="2024-06-25T00:33:45 IST" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:33:45 IST" name="launching_App" finished-at="2024-06-25T00:33:50 IST" duration-ms="5058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method signature="purchaseOrder(java.util.HashMap)[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:33:50 IST" name="purchaseOrder" data-provider="getdata" finished-at="2024-06-25T00:34:05 IST" duration-ms="15198" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{productname=ADIDAS ORIGINAL, password=Welcome@123, email=josh@yopmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- purchaseOrder -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:34:05 IST" name="close" finished-at="2024-06-25T00:34:05 IST" duration-ms="406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="launching_App()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:34:05 IST" name="launching_App" finished-at="2024-06-25T00:34:09 IST" duration-ms="3248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching_App -->
        <test-method signature="orderHistoryTest()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:34:09 IST" name="orderHistoryTest" finished-at="2024-06-25T00:34:10 IST" depends-on-methods="SeleniumRealtime.testcases.Standalone_convertTest.purchaseOrder" duration-ms="1023" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:SeleniumRealtime.testcases.Standalone_convertTest@6dab9b6d]" started-at="2024-06-25T00:34:10 IST" name="close" finished-at="2024-06-25T00:34:10 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- SeleniumRealtime.testcases.Standalone_convertTest -->
    </test> <!-- Convertedcode -->
  </suite> <!-- Realtime -->
</testng-results>
